apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    service: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      service: auth
  template:
    metadata:
      labels:
        service: auth
    spec:
      restartPolicy: Always
      containers:
      - name: udacity-capstone-auth
        image: samcowley/udacity-capstone-auth
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "64m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: session_secret 
          valueFrom:
            secretKeyRef:
              name: secrets
              key: session_secret
        - name: auth0_client_secret
          valueFrom:
            secretKeyRef:
              name: secrets
              key: auth0_client_secret
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
