apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: udacity-capstone-frontend
        image: samcowley/udacity-capstone-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        ports:
        - containerPort: 8080
        env:
        - name: session_secret 
          valueFrom:
            secretKeyRef:
              name: secrets
              key: session_secret
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
