apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    service: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: proxy
  template:
    metadata:
      labels:
        service: proxy
    spec:
      restartPolicy: Always
      containers:
      - name: udacity-capstone-proxy
        image: samcowley/udacity-capstone-proxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "64m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
