apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    service: proxy
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: http2
    port: 80
    targetPort: 80
  selector:
    service: proxy
  type: LoadBalancer
